name: Tests

on:
  push:
    tags:
    branches: [ go18 ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [6, 7]
    steps:
    - uses: actions/checkout@v2
    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-version: ${{ matrix.redis-version }}
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
        stable: true
    - name: Test
      run: make test

    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cover.out
        flags: unittests
        verbose: true
